services:
  mepa-web:
    container_name: mepa-web-dev
    image: mepa-web-dev
    build:
      context: ./
      target: dev
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: 'development'
    command: npm run dev
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      API_URL: ${API_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - mepa-network
    restart: unless-stopped

networks:
  mepa-network:
    name: mepa-network
    external: true
