services:
  mepa-web:
    container_name: mepa-web
    image: mepa-web:${TAG:-latest-dev}
    build:
      context: ./
      target: dev
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: ${NODE_ENV:-development}
    command: bash -c "npm ci && npm run dev"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.envs/.env.dev
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      API_URL: ${API_URL}
    volumes:
      - .:/app
    networks:
      - mec-energia-network
    restart: unless-stopped

networks:
  mec-energia-network:
    name: mec-energia-network
    external: true
