services:
  mepa-web:
    container_name: mepa-web
    image: mepa-web:${TAG:-latest-prod}
    build:
      context: ./
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: ${NODE_ENV:-production}
    expose:
      - ${PORT}
    env_file:
      - ./.envs/.env.prod
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    volumes:
      - nextjs_static:/app/.next/static
      - nextjs_public:/app/public
    networks:
      - proxy-network
    restart: always

networks:
  proxy-network:
    external: true

volumes:
  nextjs_static:
    name: nextjs_static
  nextjs_public:
    name: nextjs_public
