services:
  mepa-web:
    container_name: mepa-web
    image: mepa-web:latest-test
    build:
      context: ./
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: ${NODE_ENV:-test}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.envs/.env.test
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      API_URL: ${API_URL}
    networks:
      - web-network
    restart: unless-stopped

networks:
  web-network:
    name: web-network
    driver: bridge
