services:
  mepa-web:
    container_name: mepa-web-prod
    image: mepa-web-prod
    build:
      context: ./
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: 'production'
    ports:
      - 3001:3000
    env_file:
      - ./.envs/.env.prod
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    networks:
      - mepa-network
    restart: always

networks:
  mepa-network:
    name: mepa-network
    external: true
