services:
  mepa-web:
    container_name: mepa-web
    image: mepa-web:${TAG:-latest-prod}
    build:
      context: ./
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: ${NODE_ENV:-production}
    expose:
      - ${PORT}
    env_file:
      - ./.envs/.env.prod
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    labels:
        traefik.enable: "true"
        traefik.http.routers.ngnix-web.rule: "Host(`${HOSTNAME}`)"
        traefik.http.services.ngnix-web.loadbalancer.server.port: ${PORT}
        traefik.http.routers.ngnix-web.entrypoints: "websecure"
        traefik.http.routers.ngnix-web.tls.certresolver: "leprod"
    networks:
      - proxy-network
    restart: always

networks:
  proxy-network:
    external: true
